name: Update Nordic Data
on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codice
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install librerie
        run: pip install -r requirements.txt
      - name: Esegui Scraper
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python scraper.py
